W10-01: Enhance Dictionary
Vaneryn/RojakJelah pull request #21
Opened 2022-11-21 07:11 UTC by Vaneryn

1. Optimized Dictionary.aspx by adding pagination.
2. Simplified data populating using ListView.
3. Changed method of adding and handling dynamically added buttons to one that conforms to ListView.
4. Tested integration with Reports and Suggestions, LGTM (excluding null user issue, will have to check the bugfix branch again after this branch is merged).

2022-11-21 15:08 UTC, Kyewn approved these changes

2022-11-23 02:00 UTC, Kyewn requested changes
Dictionary throws error if a record has NULL example

2022-11-24 15:27 UTC, Vaneryn commented
If suggestion approval is done correctly, there should never be a NULL example, but I added a check for it just in case.

2022-11-25 03:10 UTC, Kyewn commented
Edit suggestion allows changing the example to NULL before approving. Anyway, LGTM

2022-11-25 03:10 UTC, Kyewn approved these changes

2022-11-25 05:56 UTC, merged